### ISSUE TITLE
/etc/ar-compute-engine.conf contains production-specific values

### ISSUE THREAD

**Issue by kaggis** [ARGOeu/argo-compute-engine#54]
the configuration file contains by default production-specific values and must be manually reconfigured each time is actually deployed anywhere else (devel). Should discuss how can we handle the deployment and config

**Comment by pkoro** [comment]
Deployment is done via ansible. As there are many changes in configuration files of sync and consumer components the corresponding playbooks for these packages are not yet updated, thus updating over the last couple of weeks was performed manually on the devel instances. This naturally affected the ar-compute deployment. The playbooks will be updated once all avro related developments are concluded.
